### ISSUE TITLE
Set up MUI component library

### ISSUE THREAD

**Issue by aniruddhdoki** [MrBigBrane/Prevent_T2_Web#2]
Follow the directions [here](https://mui.com/material-ui/integrations/nextjs/) to set up Material UI for Next.js. Material UI is the frontend component library that we will use to simplify our user interface development. Feel free to explore the documentation to see what kinds of components we have available.

**Comment by MrBigBrane** [comment]
Installing MUI: https://mui.com/material-ui/getting-started/installation/
(Needed before installing WITH Next.js)
