### ISSUE TITLE
Create the UI for the View Lifestyle Coach Log Page

### ISSUE THREAD

**Issue by aniruddhdoki** [MrBigBrane/Prevent_T2_Web#7]
Create the UI for the _View Lifestyle Coach Log_ page shown in the wireframe.

For the data table component, check [this](https://mui.com/material-ui/react-table/#sorting-amp-selecting) component out.

**Comment by MrBigBrane** [comment]
Data Grid component works with less dense code/more clarity https://mui.com/x/react-data-grid/sorting/
